### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by a3x-server** [cacalo/login-registro-autorizacion-node#1]
Amigo, coloca el enlace del video tutorial que hiciste en YouTube para los devs que te llegaran desde otras redes.

https://www.youtube.com/watch?v=fjuIeiA8QkE&t=3074s

**Comment by cacalo** [comment]
Gracias por el aviso!
Ya lo puse en el readme :)

**Comment by cacalo** [comment]
Además puse un link al repo del código que realmente hice en el video, porque este es el que hice de antemano para practicarlo. Te lo dejo acá por si preferís usar el otro para guiarte: https://github.com/cacalo/Registro-y-login-nodejs-express-en-vivo

**Comment by a3x-server** [comment]
Excelente, gracias.
Dejame saber si te puedo colaborar en algo.
Saludos desde Venezuela
